# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PythonCI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip wheel
        python3 -m pip install poetry
        poetry install

    #- name: Lint with pylint
    #  run: |
    #    python3 -m pylint todol
    - name: Test with pytest
      run: poetry run invoke test       
    - name: Send coverage to codecov
      run: bash <(curl -s https://codecov.io/bash)
    - name: Cache
      uses: actions/cache@v2.1.3
      with:
         # A list of files, directories, and wildcard patterns to cache and restore
         path: |
             .pytest_cache
             .hypothesis
             **/__pycache__
